#ifndef PRODUCT_H
#define PRODUCT_H


#include <stdbool.h>

#include "base.h"
#include "config.h"


typedef struct {
    unsigned int product_id;
    char name[PRODUCT_NAME_MAX];
    unsigned int unit_price;
    unsigned int quantity;
    bool is_deleted;
} Product;


typedef struct {
    Product *original_table;
    SortedIndex *sorted_by_name;
    SortedIndex *sorted_by_quantity;

    unsigned int capacity;
    unsigned int size;

    unsigned int last_id;
} ProductsTable;


ProductsTable *products_table_create(void);

// return 0, 1 if error occurs
int products_table_load(ProductsTable *products_table);

int products_table_save(const ProductsTable *products_table);

// adds new_record to table, recounts indexes, changes size
// returns id of new record or 0 if error ocurs
// *best_practise to give id from service-layer, where it will be generated by another function (DI principle)
unsigned int products_table_add(
    ProductsTable *products_table,
    const char *name,
    const unsigned int unit_price,
    const unsigned int quantity
);

// changes flag is_deleted, doesn't change size
// returns 0 or -1 if not found, 1 if error occurs
int products_table_delete_by_id(ProductsTable *products_table, const unsigned int product_id);

// changes record with product_id = product_id, recounts indexes
// returns 0 or -1 if not found, 1 if error occurs
int products_table_edit_record(
    ProductsTable *products_table,
    const unsigned int product_id,
    const char *name,
    const unsigned int unit_price,
    const bool change_quantity,
    const unsigned int quantity
);

// returns NULL if not found
Product *products_table_search_by_id(ProductsTable *products_table, const unsigned int product_id);

// print records where name == target name
void products_table_find_by_name(const ProductsTable *products_table, const char *name);

// find and show all records where quantity <= target
// showing inside
// returns 0 or 1 if erorr occurs
int products_table_filter_by_quantity(ProductsTable *products_table, const unsigned int target);

// print single entity
void product_print(const Product *p);

// print all product where is_deleted = false
void products_table_print_all(const ProductsTable *products_table);

// print records sorted by names where is_deleted = false
void products_table_sorted_by_name(const ProductsTable *products_table);

// print records sorted by quantity where is_deleted = false
void products_table_sorted_by_quantity(const ProductsTable *product_table);

void products_table_free(ProductsTable *products_table);


#endif